meta_product_name: "Traiblazr"
meta_title: "Trailblazr - Collaborative create the trip of your dreams!"
meta_description: "Trailblazr allows you to create trips, add your family and friends to them and add activities to the trip! You can make use of the built-in collaborative tools in order to make sure everybody is on board!"
meta_image: "trailblazr.png"
